### ISSUE TITLE
Memory error - parallel processing - Sobol analyze

### ISSUE THREAD

**Issue by kthorp** [SALib/SALib#140]
I get a memory error when trying to run analyze.sobol using parallel processors.  It works fine with parallel=False.  Any ideas for this problem?

```python
[kthorp@ARSAZMAR1360148 02-GSA]$ python DSSATCSM_Sobol_SA.py 
Traceback (most recent call last):
  File "DSSATCSM_Sobol_SA.py", line 159, in <module>
    result = analyze(problem, YY[:,i], calc_second_order=True,parallel=True,n_processors=8)
  File "/usr/lib/python2.7/site-packages/SALib/analyze/sobol.py", line 115, in analyze
    pool = Pool(n_processors)
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by jdherman** [comment]
Hi @kthorp thanks for opening this issue.

For my smaller sample problems I'm not able to reproduce this error (Python 2.7). What is the dimension of `YY`?

I came across this discussion which seems relevant:
http://stackoverflow.com/questions/42584525/python-multiprocessing-debugging-oserror-errno-12-cannot-allocate-memory

According to that, `os.fork()` creates a copy of the entire process. So if the program is using a lot of memory (large number of parameters and/or large number of samples), it will go over the limit.

There is a solution proposed in that thread that I'm willing to try. 

The other person who might know something about this is @bernardoct, he wrote the code for the parallel Sobol option. Bernardo, did you ever run into this out-of-memory error?

**Comment by bernardoct** [comment]
I have not run into this problem before, but I think I haven't tried large enough runs to cause memory issues either.  

Try adding "set_start_method('forkserver')" between lines 11 and 12 of file path_to_SALib_on_your_computer/SALib/analyze/sobol.py and let us know the result.

**Comment by kthorp** [comment]
YY is pretty large: a 722000 x 288 array of floats.  So, I'm likely just running out of memory when os.fork() copies the process.

I tried adding the "set_start_method" function to sobol.py, but it would not import the function. I'm running Python 2.7.  From the multiprocessing documentation (https://docs.python.org/3/library/multiprocessing.html), it appears that this function was new in Python 3.4, which explains why it won't load in 2.7.

I've tried to split to both 4 and 8 processes, leading to the same memory error.

If you're open to another option, it may work to use a process queue rather than a pool of workers: multiprocess.Process rather than multiprocess.Pool.  Is this a possibility?  I can attempt to implement if I have time in the next weeks.  I expect to be processing several very large data sets, so getting the parallel processing option to work would be ideal.

**Comment by jdherman** [comment]
Ok that makes sense. That's a big matrix. What is the ram limit that you're running into? Assuming 64-bit floats, the matrix itself would take up ~1.66 GB.

Looking at the code, I do not believe the `YY` matrix is being copied in each `os.fork()`. It would only be copying 1 column at a time, since the `analyze()` function only runs for one parameter at a time.

If the ram limit is something like 2 GB, then I don't think the problem is the parallelization strategy, it's the file-reading strategy (it should stream the big output file instead of reading it all in at once). But, if the limit is much larger than that, maybe the parallelization can be improved.

As you've found the relevant lines are here, just marking it for future reference:
https://github.com/SALib/SALib/blob/master/SALib/analyze/sobol.py#L111

I'm up for trying any solution as long as it works in both python 2/3. But before diving into the weeds on `multiprocessing`, I'd suggest:
- Check ram limit (the HPC system I use is only 2 GB, so it's not out of the question)
- Consider reading in only 1 column of the output file at a time, with `Y = np.loadtxt(....., usecols=[j])`. Get the sensitivity indices for that output. Then loop again for the next column.

If only 1 column is held in memory at a time, then the fact that `multiprocessing` is making 4-8 copies of it shouldn't matter as much.

**Comment by kthorp** [comment]
Yes, I think you're right.  I changed my code to only read one column at a time.  Then the memory issue went away.  I was originally working with a binary file, so I couldn't use numpy.loadtxt() at first.  After saving the binary to a CSV and using your suggestion, all is well.  Thanks for your help.  Issue resolved.

**Comment by jdherman** [comment]
Awesome! Good to hear. Thanks for using the library.
