### ISSUE TITLE
question: how do I select the optimum number of resamples value to use?

### ISSUE THREAD

**Issue by ivan-marroquin** [SALib/SALib#170]
Hi,

It may be possible that the results of Sobol, Morris, Delta-Moment, and Derivative-based Global Sensitivity Measure depend on the used number of resamples value. If this is the case, is there a way to estimate the optimum value?

For example, I have this problem definition:
problem= {
        'num_vars': 6,
        'names': ['Amplitude', 'Bandwidth', 'Envelope', 'Instantaneous Frequency', 'Sweetness', 'Thin Bed'],
        'bounds': [[min_amplitude, max_amplitude],
                   [min_bandwidth, max_bandwidth],
                   [min_envelope, max_envelope],
                   [min_instantaneous_frequency, max_instantaneous_frequency],
                   [min_sweetness, max_sweetness],
                   [min_thin_bed, max_thin_bed]],
        'distributions': ['norm', 'norm', 'norm', 'norm', 'norm', 'norm']
        }

The input and model data is in a 2D array of size 7344 x 7. The last column contains the model output.

What would be the optimum value for the number of resamples? is there a formula that I can use?

Many thanks,
Ivan

**Comment by jdherman** [comment]
Do you mean number of parameter samples, or number of bootstrap resamples in the analyze function?

The latter is only to determine the confidence intervals. It is not too expensive to do a large number of resamples, so > 100 is usually good. The default is 1000.

If you mean the number of parameter samples (in order to get good convergence), this is a hard question with no easy formula. I suggest trying a few sample sizes and seeing how the confidence intervals look. This is a good recent paper on the subject:
http://www.sciencedirect.com/science/article/pii/S1364815216300251

**Comment by ivan-marroquin** [comment]
Thanks for your comments and suggestions. I am interested in the bootstrap resamples in the analyze function.  I was wondering if this parameter can have a big impact in the results

**Comment by jdherman** [comment]
It will affect the confidence intervals, because it affects the estimate of the variance.

Increasing the number of bootstrap resamples should not significantly increase the computation time, because it does not require any additional model runs. So there is not much savings in choosing a low number of resamples.
