### ISSUE TITLE
Wrong values in the installaltion test question_interpretation

### ISSUE THREAD

**Issue by witteire** [SALib/SALib#172]
Hey,

I installed the SALib v 1.1.0 with pip install SALib and tested the exampled as described in the docs. 

http://salib.readthedocs.io/en/latest/getting-started.html#testing-installation

According to the docs the Sis should be [ 0.30644324  0.44776661 -0.00104936].
However, I get [ 0.03443819  0.09611386  0.12723021]. 
I use python 3.5 .2, numpy 1.13.1+mkl, scipy  0.19.1 and matplotlib 1.5.3. 
Why do I have these wrong values? 

Thanks a lot.

**Comment by jdherman** [comment]
Hi @witteire thanks for pointing this out. There was an error in that "getting started" example. The line:
```python
param_values = saltelli.sample(problem, 1000, calc_second_order=False)
```
Should not have the `calc_second_order=False` keyword argument. The problem is that the `analyze()` method later assumes a default value of `True` for this argument, so everything gets messed up because the sampling and analysis steps don't match.

I fixed this in #173, and the documentation page will probably update the next time we tag a release.
