### ISSUE TITLE
Nonuniform distributions support for method of morris sampling

### ISSUE THREAD

**Issue by filssavi** [SALib/SALib#174]
I'd like to contribute nonuniform sampling support for the method of morris.

I have hacked together a proof of concept based on the util.nonuniform_scale_samples function used in the sobol sampling algorithm.

The only problem in an otherwise trivial implementation is that the ppf function used explodes (outputs -inf or inf respectively) whenthe inputs get too close to 1 or 0
The approach I used to overcome this I just crop the allowable sample range so that only values inside a six sigma range from the mean value are returned.

Since I'm just a user of the library and I'm not extremely familiar with this method's inner workings I open this issue to discuss the enhancement before the pull request

**Comment by jdherman** [comment]
Hi @filssavi thanks for the contribution! This sounds like a good idea. Please go ahead and submit a PR. I'll also ask @calvinwhealton to join the discussion, since he implemented the nonuniform distributions for Sobol.

I looked at your branch and did not see the fix for the -inf/inf issue, was that in there too? That's also something we should have caught before.

A question to @willu47 and others. Does anyone see a case where nonuniform samples would mess up one of the methods? (Morris, FAST) For example I'm wondering if we should not include the option for Latin Hypercube, since then it would not technically be a LHS anymore.

**Comment by filssavi** [comment]
yesterday i was just playing with the code in a notebook, i just pushed to my fork the code with all the support in place and the -inf/inf issue solved

I added support to the following methods:
    -morris
    -latin hypercube
    -FAST
 
I checked the resulting distributions by plotting a histogram and they seemed ok, i haven't tested them more thoroughly, since i don't have such a strong background.

not passing the dist argument to the problem dict results in standard behaviour just as before,
