### ISSUE TITLE
delta indices not summing up to unity

### ISSUE THREAD

**Issue by witteire** [SALib/SALib#178]
Hey,

I am using the delta analysis for calculating sensetivity indices for s model with 21-30 Parameters. The delta values sum up to  1.2 - 4. As far as I understood the paper of Borgonovo 2007 they should sum up to 1, since the conditional denseties are normalized by the unconditional density. However, could it be that this is just the case if it is an additive model? 
The calculated sensitivity indices seen okay and are less than one. 

Thanks for helping out!

**Comment by jdherman** [comment]
Hi @witteire thanks for the feedback. Could you post the full console output when you get the chance, including the 1st order Sobol indices which are calculated along with the deltas. 

There are a few other open issues/PRs backing up, but I'll look into it as soon as I can.

**Comment by jdherman** [comment]
Hi @spizwhiz and @witteire ,
Sorry, this fell off the radar. As best I can tell, there is no requirement for the Delta measures to sum to one. I'm basing this on two things. First, the table in the original Borgonovo paper:

![image](https://user-images.githubusercontent.com/1936620/44872701-19318300-ac4b-11e8-802b-1b8a408c7cb2.png)

Property 3 refers to the Delta measure describing the combined interactive effects of all parameters, like an "n-th order sensitivity index". It is not the sum of all Deltas of the individual parameters (delta_i). Also, the individual delta_i's are bounded on [0,1], but of course that does not say anything about the sum.

Second, the empirical example in the Plischke paper. For the Ishigami function, the following values are reported:
![image](https://user-images.githubusercontent.com/1936620/44872870-7decdd80-ac4b-11e8-9bee-7cbece876e00.png)

Running the Delta method in SALib (example below) gives similar output, again where the deltas do not add to one:
```
Parameter delta delta_conf S1 S1_conf
x1 0.213268 0.006854 0.304961 0.012539
x2 0.352977 0.005908 0.421474 0.015439
x3 0.161495 0.006543 0.002479 0.003249
```

So the question then is what to do about this for interpretation. Out of all the SA methods I'm aware of, there is only one where the indices are expected to add to 1: first-order Sobol indices in the specific case of an additive model. In all other cases, including Morris etc., the values don't necessarily represent a fraction. Since the values themselves are not interpretable, one thing I've done in a few previous papers is to normalize the indices to the range [0,1]. (which of course does not make them add to 1, but does improve the interpretability).

I will leave this issue open in case any users have a different read. But for now I don't believe there is a bug in the code, as best I can tell.

-----------------------
minimum code example:
```python
import numpy as np 
from SALib.sample import latin
from SALib.analyze import delta
from SALib.test_functions import Ishigami

problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}

X = latin.sample(problem, 10000)
Y = Ishigami.evaluate(X)

Si = delta.analyze(problem, X, Y, num_resamples=100, 
                   conf_level=0.95, print_to_console=True)
```

**Comment by spizwhiz** [comment]
Thanks for checking back, that is very helpful.

I just wanted to make sure of one other thing -- the confidence returned is one sided, correct?

**Comment by jdherman** [comment]
Yes, all of the confidence intervals in SALib are reported as the half-width of the 95% CI by default.

**Comment by witteire** [comment]
Hi,

 

Sorry for responding so late. I forgot that I opened that question. I just want to confirm that they do not have to sum up to 1. I misunderstood it at that time. I talked to Mr. Plischke who is working together wuth Borgonovo and he reassured it. 

 

Thanks @John for the very detailed answer!

 

Von: Jon Herman [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. August 2018 21:00
An: SALib/SALib <SALib@noreply.github.com>
Cc: witteire <irene-witte@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [SALib/SALib] delta indices not summing up to unity (#178)

 

Hi @spizwhiz <https://github.com/spizwhiz>  and @witteire <https://github.com/witteire>  ,
Sorry, this fell off the radar. As best I can tell, there is no requirement for the Delta measures to sum to one. I'm basing this on two things. First, the table in the original Borgonovo paper:

 <https://user-images.githubusercontent.com/1936620/44872701-19318300-ac4b-11e8-802b-1b8a408c7cb2.png> 

Property 3 refers to the Delta measure describing the combined interactive effects of all parameters, like an "n-th order sensitivity index". It is not the sum of all Deltas of the individual parameters (delta_i). Also, the individual delta_i's are bounded on [0,1], but of course that does not say anything about the sum.

Second, the empirical example in the Plischke paper. For the Ishigami function, the following values are reported:
 <https://user-images.githubusercontent.com/1936620/44872870-7decdd80-ac4b-11e8-9bee-7cbece876e00.png> 

Running the Delta method in SALib (example below) gives similar output, again where the deltas do not add to one:

Parameter delta delta_conf S1 S1_conf
x1 0.213268 0.006854 0.304961 0.012539
x2 0.352977 0.005908 0.421474 0.015439
x3 0.161495 0.006543 0.002479 0.003249

So the question then is what to do about this for interpretation. Out of all the SA methods I'm aware of, there is only one where the indices are expected to add to 1: first-order Sobol indices in the specific case of an additive model. In all other cases, including Morris etc., the values don't necessarily represent a fraction. Since the values themselves are not interpretable, one thing I've done in a few previous papers is to normalize the indices to the range [0,1]. (which of course does not make them add to 1, but does improve the interpretability).

I will leave this issue open in case any users have a different read. But for now I don't believe there is a bug in the code, as best I can tell.

  _____  

minimum code example:

import numpy as np 
from SALib.sample import latin
from SALib.analyze import delta
from SALib.test_functions import Ishigami
 
problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}
 
X = latin.sample(problem, 10000)
Y = Ishigami.evaluate(X)
 
Si = delta.analyze(problem, X, Y, num_resamples=100, 
                   conf_level=0.95, print_to_console=True)
