### ISSUE TITLE
Method of Morris wrong distribution

### ISSUE THREAD

**Issue by filssavi** [SALib/SALib#179]
While doing a sensitivity analysis on a two input model with the Method of Morris I get unexpected results. The most influential parameter (x in the graphs) has low mu* and the less influential (y in the graphs) one has a higher mu* 

In the two images following you can see a scatter plot of the output with the two inputs. and in particular you can see that for a given `y`  the output is almost constant (less than 1 unit) while the variation with x is relevant (more than 10 units)

![Scatter1](https://user-images.githubusercontent.com/3536427/33893891-e2153aa8-df5c-11e7-9fa5-45c65deef9b5.png)

![Scatter2](https://user-images.githubusercontent.com/3536427/33893896-e2d585ec-df5c-11e7-9b6d-9501a40ba082.png)

while searching for the problem in the method of morris implementation I found this calculation where I suppose delta is the  difference between a value on a trajectory and the next

https://github.com/SALib/SALib/blob/4ef18c2346cda9bcdb84c0702a5c37a99d4ca4a4/SALib/analyze/morris.py#L257

could it be that this value of delta has to be scaled according to how the inputs range instead of keeping it in the [0 1] range? 

I did a back of the envelope calculation and by doing so i verified that by rescaling this delta the mu* have the correct order

**Comment by jdherman** [comment]
Thanks. I'm not sure I understand the problem. Regardless of the scaling of delta, the elementary effect of Y should be smaller because Z varies less in the direction of Y (even in absolute terms). 

If the library is not showing that result, then please make sure you're running a large enough sample size to get convergence, and double-check which columns are which variables. If it still doesn't make sense, post the code and I'll check it out.

The scaling method follows literature (Morris 1991; Campolongo et al. 2007).
