### ISSUE TITLE
Scaling delta in morris.analyze

### ISSUE THREAD

**Issue by fsahli** [SALib/SALib#191]
The delta parameter used in morris.analyze and morris.compute_elementary_effects is not scaled to account for the bounds of the parameters. 

In the sample code this is not a problem, because the samples are scaled at the end of the code. However, in the analyze code X is not [0,1] hypercube anymore, so delta can't be calculated as delta = grid_jump / (num_levels - 1)

Thanks and let me know if this makes sense

**Comment by willu47** [comment]
Hi @fsahli.  This issue is raised quite often.  Please read page 120 in [Saltelli et al. 2008](http://www.andreasaltelli.eu/file/repository/A_Saltelli_Marco_Ratto_Terry_Andres_Francesca_Campolongo_Jessica_Cariboni_Debora_Gatelli_Michaela_Saisana_Stefano_Tarantola_Global_Sensitivity_Analysis_The_Primer_Wiley_Interscience_2008_.pdf) and let me know if that answers your question?

They answer the question:

**Should** _delta_ **be rescaled so as to represent the actual sampling step in the
factor range of variation, or should it remain the same so as to represent the
sampling step between [0, 1] equal for each factor?**

**Comment by fsahli** [comment]
That certainly answers my question. Thank you very much!

**Comment by willu47** [comment]
Great, I'll close this issue then. Glad I could help!
