### ISSUE TITLE
RDB-fast analyze doc typo or wrong default

### ISSUE THREAD

**Issue by veeshy** [SALib/SALib#200]
https://github.com/SALib/SALib/blob/fd64136192f00a9e3e65a8c5c05e30d93ed5e750/SALib/analyze/rbd_fast.py#L14-L34 

uses M=10 as default but the doc string specifies 4. The README.md of the [code](https://github.com/Sarah-Ju/RBD-Fast) this is based on says M can be raised up to 10, I think the default should be 4 like FAST. M is usually 4 or 6 as per Plischke [2, in the rdb_fast lit] for spectrum calcs.

**Comment by celliern** [comment]
The default should be M=10 for RBD-Fast.

Usually you restrain to M=4 because the results biase increase with the number of harmonic. But this implementation unskew the results, and so it is better to take more harmonic in order to fully represent a triangle signal (at least 7, and 10 should be a good choice).

I will make a pull request to modify the doc typo.
