### ISSUE TITLE
No module named 'SALib'

### ISSUE THREAD

**Issue by YingxiaoKong** [SALib/SALib#204]
Hi,
after I use 'pip install SALib' and it said successfully installed, I import it with' import SALib' ,but it said no module named SALib. Mine is a Mac Pro. Shall I do something to fix this problem?

**Comment by jdherman** [comment]
This sounds like an error related to the python setup, not SALib specifically. See if you get the same error when installing other packages. My guess would be having multiple versions of python installed, such as the default Python plus Anaconda, and the package is only being installed to one of them.

I will close the issue because I do not believe it is related to SALib itself.
