### ISSUE TITLE
Failing to calculate sensitivity indexes with NAN values in the model results

### ISSUE THREAD

**Issue by j-chacon** [SALib/SALib#237]
I have tried to calculate the Sobol indexes with NAN values as results of the model output, which leads to NAN values of the sensitivity indexes.

A sample code is added

```
import numpy as np
import SALib as sa
from SALib.sample.saltelli import sample
from  SALib.analyze.sobol import analyze

def func(x):
    if x[0]/x[1] > 1:
        out = np.nan
    else:
        out = np.sum(x)
    return out

sa_prob = dict(num_vars = 2,
               names = ['x', 'y'],
               bounds = [[0,1], [0,1]],
               )

X = sample(sa_prob, 1000)
Y = np.array([func(Xi) for Xi in X])
out = analyze(sa_prob, Y)
```
The results of this operation may come from the fact that the functions are not suited to support operations with NAN values (np.sum and np.std among others).

**Comment by willu47** [comment]
Hi @j-chacon. Thanks for adding the issue and an example - very helpful. Have you seen #134 where this is some discussion of missing data?  We may consider SALib failing to produce results when NaN exist to be a feature, rather than a fault...  My worry is that silently producing results when there is missing data may be misleading, whereas the current situation pushes the onus back onto the user to manage their missing data in an appropriate manner.

**Comment by j-chacon** [comment]
Hi @willu47 
Thanks for your answer, indeed a really interesting discussion. 

However, I would like to point out that in some cases, the user may be interested in analysing the sensitivity of a model over a set of feasible combinations of inputs, and not over the whole (fixed) range of the variable. In other words, a non-rectangular domain. In particular, I'm approaching a problem that is quite similar to the one raised in https://github.com/SALib/SALib/issues/134#issuecomment-372028115. In this problem, it is not possible to have a functional relationship among parameters to explore the model.

From the discussion, it is possible to conclude that there may be some approaches such as redo the model runs and interpolate between the results, replacing the NAN value, or completely changing the method (https://github.com/SALib/SALib/issues/134#issuecomment-279782874). 

- Redo the model runs: Sometimes, we are just not interested (or is not physically feasible) that the model can have a certain combination of parameters. This makes the model lie beyond stability, and it would be unrealistic to force it there.
- Interpolate between the results: this approach may be suited in case that the combination of parameters is feasible, but is triggered by instabilities of the model itself. However, does not satisfy every kind of problem.
- Replace the NAN values in the result with a convenient value (https://github.com/SALib/SALib/issues/134#issuecomment-372076566): This indeed may be an option, keeping in mind that will have an effect in effectively distorting the generated sequences such as in Sobol and Morris.
- Changing the SA method: Indeed that is always a possibility.

From a more theoretical point of view, we can modify the Sobol method as proposed by Kucherenko (http://epubs.surrey.ac.uk/841382/1/Sobol%27%20indices%20for%20problems%20defined%20in%20non-rectangular%20domains.pdf), but I believe that this may take a great deal of effort at the moment.

From a pragmatic point of view, allowing to calculate the sensitivity indexes allowing NAN values, will be approaching the problem from the perspective of replacing the NAN values with a convenient value which does not have an effect in the calculation of either mean or variance (as in https://github.com/SALib/SALib/issues/134#issuecomment-372076566, but without the bias penalty of having to choose a numeric and constant value).

So, how does it sound reasonable to move from here?

Regards,

**Comment by willu47** [comment]
I think that is a reasonable rationale - and it's very useful to have this summarised and made explicit here. Many thanks for taking the time.  I'm happy to accept the pull request. Any comments or thoughts @jdherman?

**Comment by jdherman** [comment]
Thanks @j-chacon ! This is a good rationale, and this issue comes up a lot from users. A few suggestions to discuss for the PR:

1. I think it would be better for the `sobol.analyze` method to have a flag `ignore_nans=False` by default. The reason is that users may not realize there are nans in the output (due to model bugs, infeasible parameter combinations, etc.) and it would be better for them to know that, rather than silently changing the behavior of the results. Then we could make clear (maybe in the advanced readme) that this option exists to ignore nans in the calculations. 

2. In the case that `ignore_nans=False`, maybe rather than returning `Si=nan` it would be better to raise a warning or an error? This warning could inform the user about the flag option, and would be a clear way to let them know that their model output contains nans.

3. Then as @willu47 pointed out, it would be great to have tests to go along with this. For example maybe the tests could artificially put nans in the model output vector Y and make sure that the right warnings are raised, etc.

Thanks again, this change is going to be really helpful.

**Comment by j-chacon** [comment]
Hi @jdherman and @willu47 

Thanks for the positive feedback, I'm updating the pull request to include these comments. However, I think an error should be raised in case that NANs are found. 

Otherwise, we can just override the whole calculation and return the NANs directly.

Regards,

**Comment by tupui** [comment]
My 2 cents coming from SciPy where we have a few NaN policies. It's very difficult to handle and if you start to support that, you open the door to lot of different use cases users will have. e.g. in SciPy we sometimes have options to propagate NaNs, omit values, or have a sentinel. And all that for a given function. It brings up a lot of extra complexity, and we find bugs often.

Most of the time, it's easier for users to deal with cleaning their inputs. Because again, it's difficult to come up with something that would work for all use cases and things like axis, multiprocessing, etc.

IMHO, I would just raise an error if NaN values are found and invite users to use a method which is independent of that such as the method of moments.
