### ISSUE TITLE
Threshold/cut-off criteria for sensive/non-sensitive parameters with the Delta-MIM method?

### ISSUE THREAD

**Issue by TobiasKAndersen** [SALib/SALib#268]
As an alternative method to Morris method, I am using the Delta-MIM method on an aquatic model with 340 input parameters. Looking at the delta results I observe no clear demarcation of sensitive and non-sensitive parameters. Do anyone know of a threshold or cut-off criteria to use with the Delta-MIM method?

**Comment by jdherman** [comment]
Hi @TobiasKAndersen , this is a question for all SA methods, and usually requires some subjective decisions.

One way to determine insensitive parameters is to see where the confidence intervals overlap zero. The _conf values are the 95% interval for each sensitivity index, so if (delta - delta_conf) is less than zero, you can say that the parameter is not statistically sensitive.

But beyond that there are usually some subjective assumptions based on how the indices look. For example you could determine a cutoff for the "most sensitive" parameters based on the top 10% of delta values.

**Comment by TobiasKAndersen** [comment]
That sounds like a good approach! Thanks again, @jdherman !

**Comment by JoerivanEngelen** [comment]
Disclaimer: The usefulness of the following depends on your sampling scheme and GSA method, as it does for example not work for one-at-a-time methods.

At EGU2017 I saw a talk of Jiri Nossent, of which I unfortunately cannot find the abstract. 
(Instead to give him some credit a link to a paper of him: https://www.sciencedirect.com/science/article/pii/S1364815211001939)

But what he did to find a threshold for parameter insensitivity, he purposely introduced a "dummy" parameter in his Sobol analysis that did not do anything to the model. Since the Sobol analysis would always attribute some limited amount of sensitivity to a parameter, any parameter less sensitive than this dummy parameter certainly did not contribute anything to the output of interest.
