### ISSUE TITLE
Modify sample matrix before Sobol Analysis / Modificar matriz de muestra antes del análisis de Sobol

### ISSUE THREAD

**Issue by rodrigojara** [SALib/SALib#278]
Hi everyone!

I'm doing Sobol analysis using Salib and getting sample matrix using saltelli.sample function. The equation Im analyzing include a inverse error function. Before the Sobols analysis its necessary to exclude some of the samples generated by saltelli sample method so the function domain make sense. I have modified the sample matrix, by removing those samples that don't comply with the domain requirements, but I get weird Sobols indices. 

Since you can't use existing data to calculate Sobol indices like was asked in issue #211 ( like export the modified sample ), there is anyway to modified sample matrix before the Sobol analysis (sobol.analyse) ???

Thanks!

¡Hola a todos!

Estoy haciendo un análisis de Sobol usando Salib y obtengo una matriz de muestra usando la función saltelli.sample. La ecuación que estoy analizando incluye la inversa de la función de error. Antes del análisis de Sobols es necesario excluir algunas de las muestras generadas por el método de muestra saltelli para que el dominio de la función tenga sentido. He modificado la matriz de muestras, eliminando aquellas muestras que no cumplen con los requisitos del dominio, pero obtengo índices de Sobols extraños.

Ya que no puede utilizar los datos existentes para calcular los índices de Sobol tal como se menciona en el asunto #211  (como exportar la muestra modificada), ¿hay alguna forma de matriz de muestra modificada antes del análisis de Sobol (sobol.analyse) ???

¡Gracias!

**Comment by jdherman** [comment]
Hi @rodrigojara , this sounds like the same issue as having NaNs in the model output - bad samples lead to invalid model runs, which need to be replaced somehow. The main point is that you can't remove samples (rows) from the Sobol matrix, because the order needs to be preserved. 

This issue has come up a lot, and it's in our queue of things to address. If there isn't an easy way to modify the sampling ranges to avoid the NaN model runs, then check out the current list of ideas in PR #273 and see if any of them might work for your problem.
