### ISSUE TITLE
Default value for number of levels

### ISSUE THREAD

**Issue by lbteixeira** [SALib/SALib#323]
Hello, everyone.

Currently there is a default value for the number of level in the `sample` method of the subpackage `sample/morris` (`num_levels=4`). The number of levels is a fundamental aspect of this method, shouldn't we demand the user to explicitly specify it, removing this default value? This can avoid people forgetting to change this value and having unexpected results.

**Comment by ConnectedSystems** [comment]
I personally don't find this specific issue of default values to be problematic.

The user forgetting to change the value means the code will look "wrong".
Can you guess which ones below are 'incorrect' if you intended to use 8 levels?

```python
sample(problem, 100)
sample(problem, 100, 8)
sample(problem, 100, num_levels=8)
sample(problem, 100, num_levels=4)
```

I think it would be better to provide more information in the docstrings as to what combinations of trajectories/levels are appropriate rather than mandating the number of levels be user-provided.

My reasoning is that a key aspect of SALib (and why I like it so much) is it provides a relatively easy interface to sensitivity analysis work - the default values provide a base from which further exploration can be attempted.

**Comment by willu47** [comment]
Also 4 levels is the recommended value for the Saltelli version of Morris. Having these defaults nudges users into the right direction and also minimizes the number of parameters required.

**Comment by lbteixeira** [comment]
It's clear, and I agree with you. I'm going to close the issue.
