### ISSUE TITLE
Discrete variables concern

### ISSUE THREAD

**Issue by fracomp** [SALib/SALib#341]
Hi there,

I am a newbie about the topic of sensitivity analysis. However, this library looks great! 
I have some doubts in regards to discrete variables in the problem definition. I understand that you can produce your sample with uniform distribution and then round to the next integer. This makes sense. Hence, suppose we "solve this issue" and then being able to generate our outputs:
>>> Y = Ishigami.evaluate(X) _(example)_

Here is my doubt. When we perform SA with Sobol the _analyze_ function does not have any parameter in regards to the **adjusted** sample. I know that the outputs are affected by the **adjusted** samples, but the following line of code does not seem able to take into account the fact that some Input are discrete (in fact the 'dist' in the _problem definition_ will be equal to uniform)

>>> Si = sobol.analyze(problem, Y, print_to_console=True)

We can adjust parameters to have discrete values, but does the above function consider that?

Thank you

**Comment by ConnectedSystems** [comment]
Hello,

When working with discrete values I pass in the "raw" sample values rather than the adjusted sample values (which you may be doing currently, but I wasn't sure based on the example code you gave).

If you use the "typical" approach of binning the sample into discrete values, there may be bias in your sample but this can be mitigated with a large enough sample size at the risk of possibly "wasting" compute time.

I'm not aware of any issues with Sobol' analysis and discrete values, other than the above risk of sample bias and possible additional compute (which would be true for most, if not all, approaches I think). But others here may have thoughts on this.

**Comment by fracomp** [comment]
Thank you for your answer.

I hope I have explained that properly. My only concern is about the following line of code.

_Si = sobol.analyze(problem, Y, print_to_console=True)_

Although you can manipulate your samples with your desired distribution later on, there is no way to specify in the _problem_ dictionary. Hence, the above function will run with no knowledge of the modified distributions since the input samples is not a parameter of that function. 

I am wondering if this is a problem or not.

Regards,
Francesco

**Comment by ConnectedSystems** [comment]
Hi again,

My earlier response answers this (last two sentences). I've since come across this conference paper (link below) which utilizes discrete values with Sobol analysis in case of interest.

For emphasis, there is the possibility of sample bias and computational inefficiency, but to answer your question directly: no, not an issue.

https://www.computer.org/csdl/proceedings-article/wsc/1997/42780261/12OmNAiFI9N

**Comment by fracomp** [comment]
Thank you again!

**Comment by ConnectedSystems** [comment]
Hi again,

The discussion at https://github.com/SALib/SALib/issues/195 may also be of interest.

I'm going to close this but feel free to re-open.
