### ISSUE TITLE
[Feature Request] Extended Fourier amplitude sensitivity test - eFAST

### ISSUE THREAD

**Issue by giupardeb** [SALib/SALib#404]
Hi guys, I'm looking for a function to run a eFAST function. Is there a plan to develope this analysis in your library? If not, can you suggest me a good library that implements it?

Thanks!

**Comment by ConnectedSystems** [comment]
Hello,

We do not currently have a roadmap for this analysis method, and I'm not aware of a Python package that has eFAST implemented unfortunately.

The R `sensitivity` package has eFAST (as [fast99](https://www.rdocumentation.org/packages/sensitivity/versions/1.4-1/topics/fast99))

The following Julia packages have eFAST as well:

https://github.com/SciML/GlobalSensitivity.jl
https://diffeq.sciml.ai/stable/analysis/global_sensitivity/

Hope this helps

**Comment by sofianehaddad** [comment]
Hi,
You might have a look at [openturns extended FAST](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.FAST.html)

**Comment by giupardeb** [comment]
> Hi,
> You might have a look at [openturns extended FAST](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.FAST.html)

Oh thank you so much!

**Comment by ConnectedSystems** [comment]
Hi @giupardeb @sofianehaddad 

It was brought to my attention that the implementation in SALib is actually eFAST.

From my (faulty) memory I thought the FAST method in SALib only returned first order sensitivities (S1), but turns out I was thinking of the RBD-FAST method (as implemented in SALib). 

I will be making patches to the docstrings to make this clearer.

Apologies for any confusion/inconvenience caused.

**Comment by ConnectedSystems** [comment]
Docstrings updated. Thanks @giupardeb for bringing this to our attention.
