### ISSUE TITLE
get -inf sample

### ISSUE THREAD

**Issue by fuxinniu** [SALib/SALib#470]
I am trying to generate normal distribution samplings. 

problem = {
    'num_vars': var_num,
    'names': var_name,
    'bounds': var_combinedB,
    'dists': var_dist
}
feed = 50
var_saltelli_sampling = saltelli.sample(problem, feed)

Here is the bounds:
![image](https://user-images.githubusercontent.com/58092272/131869843-3c78dce4-bc2d-464f-908b-b270fdbaa0de.png)

But I got the -inf sampling at first 67 points. 

![image](https://user-images.githubusercontent.com/58092272/131869961-0ea33d04-dd01-43a9-818b-5cb76ca8cb3d.png)

Anyone know what is wrong with it?

So appreciate. 

Frank

**Comment by ConnectedSystems** [comment]
Hi @fuxinniu 

I believe you are using the most recent version of SALib (1.4.0.x), but let me know if this is not the case.
This might be caused by the new sampling rules incorporated based on feedback.

Specify `skip_values >= N`, where `N` is `feed` in this case.

We now recommend that both `skip_values` and `feed` should be a power of 2 (e.g., 1024, 2048, etc).

Something like:

```
feed = 1024
var_saltelli_sampling = saltelli.sample(problem, feed, skip_values=2048)
```

This is handled somewhat automatically in the upcoming v1.4.1 onwards

If of interest, you can read the new documentation [here](https://github.com/SALib/SALib/blob/70420a0b3836c470f21076460ae4b617c7d8c895/src/SALib/sample/saltelli.py#L15)

**Comment by fuxinniu** [comment]
@ConnectedSystems 

Thanks for your response. 

After using the feed and skip_values with a power of 2, that issue is gone. 


But another issue that I did get the normal distribution. It is uniform distribution even I defined "dists" as "norm"

![image](https://user-images.githubusercontent.com/58092272/132045228-5bd1a503-ac5a-47da-ae8a-e40c4274c784.png)

Any suggestions.

Thanks a lot. 

Frank
