### ISSUE TITLE
Can SALib be used to conduct Sensitivity Analysis to Evaluate Multinomial Logistic Regression equation?

### ISSUE THREAD

**Issue by glara2** [SALib/SALib#485]
Hi,

I am brand new to using SALib and am having a tough time figuring out how to use it in order to evaluate my data and model (wondering if it's even possible). 
 
I have a few questions (apologies for my ignorance):

1. When defining the problem, I need to create a dictionary with my model predictors and the min/max values for each, correct?

Here is an example of what that looks like in my case (two categorical variables, one continuous): 

```python
problem = {
    'num_vars': 3,
    'names': ['var1', 'var2', 'var3'],
    'bounds': [[0.0, 1.0],
               [1.0, 6.0],
               [44.0, 97.0]]
```

Is this correct?

Second, in the documentation it appears that saltelli.sample() is being used as a data set upon from which parameter samples are pulled. It appears to me that the Ishigami formula is then being iteratively applied using the parameter values established in "problem". Is my understanding correct or am I totally off?

In my case, I am using statsmodels to run multinomial logistic regression. Is it possible to follow the format outlined in the SALib documentation to evaluate an mnlogit model on my data set? If yes, can anyone give me an easy to follow example? Am I completely misunderstanding how SALib works?

Thanks in advance for your help and I apologize if any of these are stupid questions.

**Comment by ConnectedSystems** [comment]
Hi @glara2 

> Is my understanding correct or am I totally off?

You're spot on, really. There are three things I'd like to add

1. The default is to take a uniform distribution. It is possible to change the sampling distribution (with some caveats) by adding a `dists` entry to the dictionary. This changes how the `bounds` entry is interpreted.

https://salib.readthedocs.io/en/latest/advanced.html#generating-alternate-distributions

2. You can also group parameters together by specifying a `groups` entry (may not be so relevant here, but just so you know)

https://salib.readthedocs.io/en/latest/advanced.html#group-sampling-sobol-and-morris-methods-only

3. Most, if not all, SA methods assume continuous inputs/outputs. A simple and pragmatic workaround is to map the categorical values to an integer (as you've already done), specify +1 to the upper bound, and take the `floor` of the sample input prior to running the target model to "shift" the sample input to the target integer.

For example, say you have 4 possible categorical values for a parameter: `(A, B, C, D)`, you would map these to `(0, 1, 2, 3)`, and specify the range as `[0, 3+1]`.

Note that the mapping is conceptual only (i.e., keep it in mind) - you don't need to change your code.

Then:

```python

# I'm assuming var1 and var2 are the categorical parameters (note the +1 for each)
problem = {
    'num_vars': 3,
    'names': ['var1', 'var2', 'var3'],
    'bounds': [[0.0, 1.0+1],
               [1.0, 6.0+1],
               [44.0, 97.0]]

# Generate samples
param_values = saltelli.sample(problem, 1024)

# Make a copy here for provenance
# Additionally, some methods, like Morris or RBD-FAST, require the original inputs for analysis so its useful to 
# have a copy of the original input set
modified_values = param_values.copy()

# We then `floor` the values for the categorical inputs
# e.g., everything < 1 will be mapped to 0, between 1.0 and 2.0 as 1, etc
modified_values[:, 0:2] = np.floor(modified_values[:, 0:2])

# Then call the model with the modified inputs
Y = your_model(modified_values)

# Conduct analysis
Si = sobol.analyze(problem, Y)

# Display results
print(So.to_df())
```

You might be interested in this discussion where I provide a similar example but show the example floored values.

- https://github.com/SALib/SALib/issues/400

The caveat I note in the above is that taking the `floor` may bias the samples. Because the values get "shifted" downward, you may end up taking more samples from a parameter over all others, or you may take duplicate samples: 

```bash
[0.5, 0.6] => [0, 0]
[0.3, 0.9] => [0, 0]
[1.1, 2.8] => [0, 1]
[1.1, 2.1] => [0, 1]
```

Thus, you're "wasting" compute time and the number of usable samples taken can be a lot smaller than what you might expect.

Others have suggested pre-processing in these cases, wherein you identify the duplicate entries and only run the model once for each of those.

Doing this may take more time than its worth if your model is runs very fast, although it is true that analyzing the number of duplicates will be helpful in understanding if the samples are biased towards one parameter.

Let me know if you have any other questions.

**Comment by ConnectedSystems** [comment]
Hi @glara2 

Would you mind reformatting your post above to follow github markdown? It will make it that little bit easier for me to follow.

https://guides.github.com/features/mastering-markdown/

See especially the section on syntax highlighting

I'll have a closer look when I can tomorrow

**Comment by glara2** [comment]
Yes, I'm very sorry. Working to fix this now, new to posting here.

**Comment by ConnectedSystems** [comment]
Hi @glara2 

See [this gist](https://gist.github.com/ConnectedSystems/b6e26053201714e779c1021e95d7c689) for a very basic example application of SA on an MNLogit model.

There are other ways you could apply SA to an MNLogit model but it gets more involved.
Ultimately, it depends on what you want to do.

> Does the n size of the sample matter for SA?

Yes, it does. How big or large `N` should be is a matter of debate, but generally it relates to how many parameters you have. The more parameters a model has, the more samples you need, but it can depend on how your target model behaves too.

An unsatisfying answer would be that N should be as small as you can get away with.

> My overall goal is to perform a sensitivity analysis on a subset (sample) of our longitudinal data in order to establish how different values of our predictors impact our categorical dependent variable

For this overarching goal, you could adapt the extended example from our [documentation here](https://salib.readthedocs.io/en/latest/basics.html#another-example).

Within the example linked above, the influence of parameters on `y` in relation to parameter `x`, and the relationship of `x` to other parameters is investigated. Conceptually, the approach there would be the same (or at least very similar) for investigating the effect on a course letter grade.

> In the context of SALib, what is the best way of selecting a model for the sensitivity analysis?

Usually it's the other way around: A model is not selected for SA, rather SA is used to assess available models, for a range of purposes.

What you are describing is what we would call factor mapping: mapping the effect on an output (the dependent variable) back to a parameter or set of parameters (the explanatory variables). In other words: how much of an effect does a parameter have on a given output (and where/when is it important)?

Hope this helps

**Comment by ConnectedSystems** [comment]
Hi @glara2

I'm going to assume you managed to find a suitable path forward, so will close this issue.

All the best!
