### ISSUE TITLE
Group parameter sampling might not work as intended for morris method

### ISSUE THREAD

**Issue by cnaegeli** [SALib/SALib#488]
I am using the morris method with grouped parameters in order to reduce the number of parameters as the model I am applying the method to takes quite long to run so I am limited in the number of model iterations I can reasonably perform. Reading a bit about how grouped parameters should work, I expected that each parameter in a group is moved together with all other parameters in the group and in the same direction. As far as I can tell this is however not the case and the individual parameters are moved independent from each other.

If I take the example from the documentation:
```
problem = {
    'groups': ['Group_1', 'Group_2', 'Group_2'],
    'names': ['x1', 'x2', 'x3'],
    'num_vars': 3,
    'bounds': [[-3.14, 3.14], [-3.14, 3.14], [-3.14, 3.14]]
}
```
This is the result I  get when running `morris.sample(problem, 100, num_levels=4)`
```
         x1        x2        x3
0  3.140000 -1.046667  3.140000
1  3.140000  3.140000 -1.046667
2 -1.046667  3.140000 -1.046667
3 -1.046667  1.046667  1.046667
4  3.140000  1.046667  1.046667
```
However I would have expected more something like this, where the parameters x2 and x3 are always moved in teh same direction to the same extent:
```
         x1        x2        x3
0  3.140000 -1.046667  -1.046667
1  3.140000  3.140000  3.140000 
2 -1.046667  3.140000 3.140000 
3 -1.046667  1.046667  1.046667
4  3.140000  1.046667  1.046667
```

**Comment by ConnectedSystems** [comment]
Hi @cnaegeli could you let me know which paper you're referring to?

**Comment by cnaegeli** [comment]
Hi
Thanks for your answer. I was reading in the book in Saltelli et al.´s book on global sensitivity analysis:
http://www.andreasaltelli.eu/file/repository/A_Saltelli_Marco_Ratto_Terry_Andres_Francesca_Campolongo_Jessica_Cariboni_Debora_Gatelli_Michaela_Saisana_Stefano_Tarantola_Global_Sensitivity_Analysis_The_Primer_Wiley_Interscience_2008_.pdf
But now when rereading it I noticed that it actually mentioned that the parameters also move in different directions. So I guess I just missed that when first looking into the methodology. 

I am guessing I am using the default version since I did not specify any changes but based my set up based on the example in the documentation. Is there a way to change the sampling method? I did not see anything specified in the documentation on this. 

Can you elaborate a bit on why the method allows grouped parameters to move in different directions? For me this seems counter intuitive as some of the effect is "averaged" out by factors in a group moving in different directions. At least that is what happens in my analysis. Or am I simply using grouped parameters wrong and they do not necessarily mean parameters that are correlated with each other?

**Comment by ConnectedSystems** [comment]
By documentation I assume you're referring to the ReadTheDocs page or similar.  

We're going through a process of expanding documentation, but I encourage you to read the docstrings via the [Python REPL](https://jakevdp.github.io/PythonDataScienceHandbook/01.01-help-and-documentation.html#Accessing-Documentation-with-?) or by looking at the source code.

Generally the docstrings have more detail than what is provided in the readme or documentation site, with the latter focusing more on the practical usage examples.

> Can you elaborate a bit on why the method allows grouped parameters to move in different directions?

Allowing constituent parameter values to move in independent directions can maximize the parameter space explored for a given specified number of samples compared to moving them in the same direction. The idea presented in the paper (linked to in my previous comment) is to min max the number of trajectories relative to their spread in parameter space.

The example is to generate a high number of trajectories (500 to 1000 in the paper) and then select a handful of `r` trajectories (10 in the paper) that maximizes the "spread" throughout parameter space (i.e., minimize the number of trajectories and maximize the area scanned).

> For me this seems counter intuitive as some of the effect is "averaged" out by factors in a group moving in different directions

I take it you're focusing on the μ (mu) metric? You're right that it could be "averaged" out because it is the mean of the distribution. Campolongo et al. (again in the paper I link to above) state that μ can't be used in cases where parameters are grouped precisely because of this averaging cancels out the effects. They introduce μ<sup>*</sup> (mu star), which is the mean of the distribution of absolute values, and so is a more reliable indicator when effects have opposite signs.
If the direction of effects is important, they suggest comparing μ<sup>*</sup> against μ (if both are high, then the directions are the same).

Note that σ (the standard deviation of the distribution) is still relied on to indicate interactions between factors.

> they do not necessarily mean parameters that are correlated with each other?

That's correct, it doesn't necessarily mean that the factors are correlated. Parameters are grouped for a purpose, not by a given property or characteristic (although they can be grouped by these for a given purpose).

Often the primary purpose is to reduce the number of samples/model evaluations needed to gain indicative results. There can be other secondary purposes as well though.

There are studies which initially group all climatic factors together, all economic factors together, all hydrological factors together, and see which system is having more of an effect on outcomes, and under what conditions, followed with more targeted analyses. 

On the other end, groups could be defined as being made up of factors with similar levels of sensitivity (or correlations, for example) which is determined through an iterative process.

All that to say if you state "I'm grouping all these factors together because I assume they are correlated for [some purpose]", so long as you can defend how you came to that assumption, the logic is reasonable, and fits the purpose, then sure, you can do that.

**Comment by ConnectedSystems** [comment]
My apologies @cnaegeli turns out I misremembered and it is Ruano's method (https://doi.org/10.1016/j.envsoft.2012.03.008) that is the default.

Everything else I wrote above remains true, however.

**Comment by ConnectedSystems** [comment]
#489 may be of interest to you, although I am rehashing the content above.

**Comment by ConnectedSystems** [comment]
Hi @cnaegeli 

Alternate distributions are only supported for the Saltelli approach at the moment.

See [here](https://salib.readthedocs.io/en/latest/advanced.html#generating-alternate-distributions) for a brief usage example.

**Comment by ConnectedSystems** [comment]
Thanks for the discussion @cnaegeli 

I will close this issue as I think we've taken this as far as we can for now.
