### ISSUE TITLE
How to perform sensitivity analysis for a ODE system which without analytical solutions

### ISSUE THREAD

**Issue by ZSTanone** [SALib/SALib#507]
I would appreciate it if you could provide me a simple example for my reference

**Comment by ConnectedSystems** [comment]
I did see this come up but then forgot to respond, apologies.

The process should be identical as with any other model. If you could provide a small working example, I can mock up a more detailed explanation of the process. Otherwise the examples (linked below) should be enough to get you started.

https://salib.readthedocs.io/en/latest/basics.html#run-model

https://github.com/SALib/SALib/tree/main/examples
