### ISSUE TITLE
Sobol fails when result has multiple columns

### ISSUE THREAD

**Issue by Ge0rges** [SALib/SALib#517]
Running `Sobol analyse` fails when my results array has multiple columns (i.e. my model has multiple output for one set of paramaters).

Error occurs on line 206 of Sobol.py with error:

```
  File "model.py", line 182, in sensitivity_analysis
    Si = sobol.analyze(problem, results)
  File "python3.8/site-packages/SALib/analyze/sobol.py", line 98, in analyze
    A, B, AB, BA = separate_output_values(Y, D, N, calc_second_order)
  File "python3.8/site-packages/SALib/analyze/sobol.py", line 206, in separate_output_values
    AB[:, j] = Y[(j + 1):Y.size:step]
ValueError: could not broadcast input array from shape (32,3) into shape (96,)
```

**Comment by ConnectedSystems** [comment]
When using the procedural approach, it is expected that you will apply the analysis to each output manually.

See the example underneath the text "The triad of sampling, evaluating and analysing becomes:" on [this page].(https://salib.readthedocs.io/en/latest/basics.html#another-example)

Otherwise, SALib has an interface that simplifies some aspects of its usage.

You can see an example application with this interface [here](https://github.com/SALib/SALib/blob/main/examples/Problem/multi_output.py).

**Comment by ConnectedSystems** [comment]
Closing this as I'm assuming you have arrived at a good solution. Thanks for using SALib.
