### ISSUE TITLE
weird values for sobol indices

### ISSUE THREAD

**Issue by tanguyen77** [SALib/SALib#549]
Hi 
i am trying to do a gsa for my problem where the varying parameters are control tuning parameters and each evaluation results from a closed loop simulation.

I first started by latin hypercube sampling and emukit.. generated 500 samples and ran their code. Gave me nans for the sobol indices. Then switched to salib, tried to reuse the generated data because it takes long to generate the data. 
Started with the ishigami template but put my data in instead and had to cut the data because it had to be 2^N.. the first thing i was wondering about was that sobol.analyze() does not care about the x-values. It just needs the y-values to calculate the sobol indices.. so it assumes I sampled my problem well enough? 

This is the code that I used, and the sobol indices that I got:

problem = {
    'num_vars': 6,
    'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    'bounds': [[0., 1000.],
               [0., 1000.],
               [0., 1000.],
               [0., 1000.],
               [0., 1000.],
               [0., 0.04]]
}

test_x = loadmat('C:/Users/ng/_projects/b_bay_opt/c_code/gsa/Cycle_Step2tp40_500/dataset_x.npy')
x = test_x['dataset_x'][0:448]
test_y = loadmat('C:/Users/ng/_projects/b_bay_opt/c_code/gsa/Cycle_Step2tp40_500/eta_fchv.npy')
Y = test_y['eta_fchv'][0:448]
Y = Y.reshape(448)

Si = sobol.analyze(problem, Y)

print(Si['S1'])
print(Si['ST'])

[ 0.29262398 -0.22875508 -0.17203186  0.00162322 -0.11616293  0.13569358]
[0.38099367 0.49931304 1.09592463 0.76224573 0.80960862 1.83457991]

The first order sobol indices do not sum up to 1 and some of them are negative.. I'm afraid I am doing multiple things incorrectly. I was wondering if I should do some scaling for example? But I did not really know how.

Then tried the delta method and got completely different values, which still do not sum up to 1. It left me even more confused as the values are so different. Can someone help? 

problem = {
    'num_vars': 6,
    'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    'bounds': [[0., 1000.],
               [0., 1000.],
               [0., 1000.],
               [0., 1000.],
               [0., 1000.],
               [0., 0.04]]
}

test_x = loadmat('C:/Users/ng/_projects/b_bay_opt/c_code/gsa/Cycle_Step2tp40_500/dataset_x.npy')
x = test_x['dataset_x'][0:448]
test = loadmat('C:/Users/ng/_projects/b_bay_opt/c_code/gsa/Cycle_Step2tp40_500/eta_fchv.npy')
Y = test['eta_fchv'][0:448]
Y = Y.reshape(448)

Si = delta.analyze(problem, x, Y, print_to_console=True)

       delta  delta_conf        S1   S1_conf
x1  0.089815    0.030323  0.024389  0.036600
x2  0.042929    0.027308  0.013887  0.024946
x3  0.064546    0.019121  0.007900  0.017212
x4  0.109812    0.027956  0.013943  0.027445
x5  0.239361    0.032744  0.435020  0.100515
x6  0.062118    0.029425  0.069407  0.056608

Thanks!

[Cycle_Step2tp40_500.zip](https://github.com/SALib/SALib/files/10213528/Cycle_Step2tp40_500.zip)

**Comment by tupui** [comment]
Hi @tanguyen77, thanks for reporting.

The documentation could be improved here, but `sobol.analyze` requires `Y` to have been created following a specific scheme which is not a pure LHS. There is a convenient function to help which is `saltelli.sample`, but you will need to re-launch your simulations.

The formulas used to compute Sobol' indices need to work with 3 (or 4 if you want second order indices) matrices: A, B and AB which is a mix of A and B. See wiki for instance which has a nice visual representation of the sampling required https://en.wikipedia.org/wiki/Variance-based_sensitivity_analysis

If you cannot make new experiments, I would suggest to make a meta model and use this meta model to compute indices. This would be very handy as you would be able to verify the convergence of the indices. Note that 500 samples is not enough, with 6 variables, I would at least go with 10 000... And this is why a meta model might be needed.

Meta model: popular options are Gaussian Processes regressor (very easy and available with Scikit-Learn), polynomial chaos and RBF.

Moment based indices are cheaper to use (still a surrogate might be a good idea) and indices are not supposed to sum to 1. With 500 samples, it might be enough and the output might be closer to be converged.

Last note: the summing to 1 and positiveness of the Sobol' indices is difficult to control due to numerical errors. It usually indicate that you are not converged.

**Comment by ConnectedSystems** [comment]
Just to add to what @tupui has said, SALib also offers PAWN which is moment-independent and can work with a given sample set.

You might also try the HDMR method which produces a surrogate. Although in my experience it is highly memory intensive, it may be workable given you have six variables.

**Comment by ConnectedSystems** [comment]
Agreed.

@tanguyen77 feel free to reach out if you have any follow up questions, but I will close this issue now.
