### ISSUE TITLE
Duplicate values in sample.saltelli

### ISSUE THREAD

**Issue by Rishitha-28** [SALib/SALib#622]
Hello,
I am conducting a sensitivity analysis on watershed parameters using Sobol's method in hydrological modeling. For this purpose, I have been utilizing the 'SALib.analyze.sobol()' function along with the sample generation functions 'SALib.sample.saltelli()' and 'SALib.sample.sobol()'.

While generating parameter values with these functions, I noticed a significant number of duplicate entries in param_values—approximately one-third of the total Y.size. I attempted to adjust the skip_values parameter, but the issue persists.

Could you please provide insights into why these duplicate values might be occurring? Additionally, how might these duplicates impact the validity and accuracy of the sensitivity analysis?

Thank you in advance!

**Comment by tupui** [comment]
Hi 👋 thanks for reporting.

Do you have an example to show maybe?

Duplicates on some axis are normal because the Saltelli sampling is constructed like that, you have two independent matrices A and B, then combine these to have AB and BA. The combination is just a permutation of columns so looking at a single axis of the whole sample would have a lot of duplicates. But each sample should be unique.

**Comment by Rishitha-28** [comment]
Hello,

Thank you for the prompt response. 
I can show you a basic example of 2 parameters:

![image](https://github.com/SALib/SALib/assets/156133337/e29d35af-dd79-409f-9a5f-adeee9027967)
Output:
>>length of param_values = 1536
>>Total number of duplicates = 512

I tried it with a smaller sample size to see repeated values. 
Smaller Sample Size:
![image](https://github.com/SALib/SALib/assets/156133337/31754aa5-f89a-4e08-9115-8fbcd03d56a1)
Highlighting a few for your reference :)
![image](https://github.com/SALib/SALib/assets/156133337/cd7ef441-3e69-4d27-8a2a-07ff4b71e19e)

Thank You!

**Comment by tupui** [comment]
I see. It's because you have just 2 parameters and are asking for second order indices. We don't prevent people from asking that, but it does not make much sense to try compute that. Like `x1|(x1,x2)` would not really make sense. It just happens to work as a corner case.

@ConnectedSystems unless I missed something, maybe we should add a check?

**Comment by Rishitha-28** [comment]
I hadn't realized that the sampling would change when requesting second-order indices.
I've now set duplicates to false, so the issue is resolved.
Thank you very much!
