### ISSUE TITLE
FAST for variables with Gaussian distribution

### ISSUE THREAD

**Issue by mastras** [SALib/SALib#91]
Hello!

I found your library to be of great use. Thank you for sharing!

However, I wondered whether it might be possible to also implement Gaussian / normal distributed variables for FAST in `sample.fast_sampler`. For instance, this could be implemented using the Inverse Cumulative Distribution Function obtained with `scipy.stats.norm.ppf`.

**Comment by willu47** [comment]
Hi @mastras.  Thanks for your question.  At the moment, we've left the generation of distributions for end users to implement.  This is intentional, as it could potentially just duplicate work that end users have already done.  However, if there's enough demand, we could implement a module which would allow you to define distributions in the parameter file and return samples that are not just uniform.

**Comment by jdherman** [comment]
Hi @mastras, just to second Will's point -- you're right that this is possible, so if you use SALib to sample a uniform random variable on [0,1], you can do the transformation yourself at the beginning of your model code. (Or, right before you save the parameter values to a file, if your model is in some other language than Python).

We'd prefer to leave this to the user, because these transformations are largely implemented in scipy, and the number of distributions that people might want to use is potentially endless! Having the uniform sampling as the basis for the library allows everyone to come up with their own transformations if needed, without making the sampling options too verbose.

Thanks for using the library!
